### ISSUE TITLE
lab3 code may has some error

### ISSUE THREAD

**Issue by parkma99** [sberkun/61b_rust_skeletons#1]
```rust
pub fn get_last(&self) -> Option<&T> {
        self.items.last()
    }
pub fn get_last_mut(&mut self) -> Option<&mut T> {
        self.items.last_mut()
}
```

in `alistnoresizing.rs`

this code may not get the correct lat element.

**Comment by sberkun** [comment]
Thanks for the catch! ironic how I had bugs in a lab about debugging

I just fixed all 3 implementations ([this commit](https://github.com/sberkun/61b_rust_skeletons/commit/cac490a795256f448f38845ec420707ee202ae5a)), feel free to let me know if anything is still broken
